version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - Inception
    restart: on-failure
    expose:
      - "3306"
    image: mariadb
    container_name: mariadb

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes: 
      - wordpress:/wordpress
    networks:
      - Inception
    restart: on-failure
    depends_on:
      - mariadb
    expose:
      - "9000"
    image: wordpress
    container_name: wordpress
    
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes: 
      - wordpress:/wordpress
    networks:
      - Inception
    restart: on-failure
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/iortega/data/mariadb
      o: bind
    name: mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/iortega/data/wordpress
      o: bind
    name: wordpress
      

networks:
  Inception:
    driver: bridge